 
name: CAPS CI/CD Pipeline

on: [push, pull_request]  # Run on every push and PR

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: caps_db
        ports:
          - "3307:3306"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, pdo, pdo_mysql, intl, zip

      - name: Install dependencies
        run: |
          cd caps-backend
          composer install

      - name: Run backend tests
        run: |
          cd caps-backend
          php artisan test

  frontend-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd caps-frontend
          npm install

      - name: Run frontend tests
        run: |
          cd caps-frontend
          npm test
