name: CI/CD Pipeline for CAPS Website

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on PRs to the main branch

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: npm run build

      - name: Deploy Frontend
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.YOUR_API_TOKEN }}" https://your-deployment-url.com

  backend:
    runs-on: ubuntu-latest
    needs: frontend  # Backend will run after the frontend job succeeds
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: |
          composer install --no-interaction

      - name: Run Backend Tests
        run: |
          php artisan migrate --env=testing
          php artisan test

      - name: Build Backend Docker Image
        run: |
          docker build -t backend-image ./backend
          docker run -d --name backend-container backend-image

      - name: Deploy Backend
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.HEROKU_API_TOKEN }}" https://your-deployment-url.com
